// 1. Challenge adında bir değişken tanımlayın ve '30 Days Of JavaScript' başlangıç ​​değerine atayın.
var challange =  '30 Days Of JavaScript';

// 2. console.log() kullanarak tarayıcı konsolunda değişkeni yazdırın,
//console.log(challange) 

// 3. console.log() kullanarak tarayıcı konsolunda dizenin length değerini yazdırın,
// console.log(challange.length)

// 4. toUpperCase() yöntemini kullanarak tüm dize karakterlerini büyük harflerle değiştirin,
console.log(challange.toUpperCase());

// 5. toLowerCase() yöntemini kullanarak tüm dize karakterlerini küçük harflerle değiştirin,
console.log(challange.toLowerCase());

// 6. substr() veya substring() yöntemini kullanarak string'in ilk kelimesini kesin-silin (dilimleyin)
